config/routes.rb
Rails.application.routes.draw do
  get 'favorites/new'
  devise_for :users
  get 'home/about' => 'homes#about'
  root 'homes#top'
  resources :users,only: [:show,:index,:edit,:update] do
   resource :relationships, only: [:create, :destroy]
   get 'follow' => 'relationships#follow', as: 'follow'
   get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :relationships, only: [:index]
  resources :books  do
   resources :comments, only: [:create, :destroy]
   resource :favorite, only: [:create, :destroy]
  end
  post 'book/:id' => 'favorites#create', as: 'create_favorite'
  delete 'book/:id' => 'favorites#destroy', as: 'destroy_favorite'
  root 'homes#top'
  get '/search' => 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image, destroy: false
  validates :name, length: {maximum: 20, minimum: 2}
  validates :name, uniqueness: { message: "Name has already been taken" }
  validates :introduction, length: {maximum:50}
  def favorited_by?(book_id)
   favorites.where(book_id: book_id).exists?
  end
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def new
    @user = User.new
    flash[:notice] = "Welcome! You have signed up successfully."
  end

  def create
    flash[:notice] = "You have created book successfully."
    @user = Users.new(users_params)
    @user.users_id = current_users.id
  if @user.save
    redirect_to books_path
  else
     render :create
  end
   current_user.follow(params[:user_id])
   redirect_to request.referer
  end

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @users = User.new
    @comments = @book.comments
  end

  def destroy
    flash[:notice] = "Signed out successfully."
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end

  def update
    flash[:notice] = "You have updated user successfully."
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user.id)
    else
     render :edit
    end
  end
  def edit
    @user = User.find(params[:id])
    if @user != current_user
    redirect_to user_path(current_user.id)
    end
  end
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
 
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        <% unless current_user == user %>
        <% if current_user.following?(user) %>
        <td>
          <%= link_to "フォローしない", user_relationships_path(user.id), method: :DELETE, remote: true %>
        </td>
        <% else %>
        <td>
          <%= link_to "フォロー", user_relationships_path(user.id), method: :POST, remote: true %>
        </td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>
	    name
	   </th>
	  <th>
	   <%= user.name %>
	  </th>
  </tr>
  <tr>
	  <th>
	    introduction
	  </th>
	  <th>
	    <%= user.introduction %>
	  </th>
  </tr>
  <tr>
  	<th>
	  	follows
	  </th>
	  <th>
	  	<%= link_to user_follow_path(user.id) do %>
	  	<%= user.followings.count %>
	  	<% end %>
	  </th>
  </tr>
  <tr>
  	<th>
	  	followers
	  </th>
	  <th>
	  	<%= link_to user_followers_path(user.id) do %>
	  	<%= user.followers.count %>
	  	<% end %>
	  </th>
  </tr>
</table>
  <th>
  	<% unless current_user == user %>
  	<% if current_user.following?(user) %>
  	<%= link_to "フォローしない", user_relationships_path(user.id), method: :delete, class: 'btn btn-info btn-lg' %>
　　<% else %>
  　<%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success btn-lg' %>
　　<% end %>
　　<% end %>
　</th>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %>
</div>

app/views/users/edit.html.erb
<p></p>
<h2 style="text-align:center">User info</h2>
<div class = "text-danger">
 <% if @user.errors.any? %>
 <%= @user.errors.count %>
 error prohibited this obj from being saved:
 <% @user.errors.full_messages.each do |message| %>
    <li>
     <%= message %>
    </li>
  <% end %>
  <% end %>
 </div>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
     <%= render 'info', user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
     <h2>Users</h2>
     <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>