config/routes.rb
Rails.application.routes.draw do
  get 'favorites/new'
  devise_for :users
  get 'home/about' => 'homes#about'
  root 'homes#top'
  resources :users,only: [:show,:index,:edit,:update] do
   resource :relationships, only: [:create, :destroy]
   get 'follow' => 'relationships#follow', as: 'follow'
   get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :relationships, only: [:index]
  resources :books  do
   resources :comments, only: [:create, :destroy]
   resource :favorite, only: [:create, :destroy]
  end
  post 'book/:id' => 'favorites#create', as: 'create_favorite'
  delete 'book/:id' => 'favorites#destroy', as: 'destroy_favorite'
  root 'homes#top'
  get '/search' => 'searches#search'
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    def favorited_by?(user)
     favorites.where(user_id: user.id).exists?
    end
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
     render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @booker = Book.find_by(params[:id])
    @comment = @booker.comments
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comments = @book.comments
    @comment = Comment.new
  end

  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to books_path
  end

  def update
    flash[:notice] = "You have updated book successfully."
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def edit
    @book = Book.find(params[:id])
     @book_new = Book.new
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class=<%= 'favorite_buttons_' + book.id.to_s %> >
          <%= render "favorites/book-favorite", book: book, user: current_user %>
        </td>
        <td>
            コメント数: <%= book.comments.count %>
          </td>
        </td>
        </td>
        <td>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_show-comment.html.erb
<% comments.each do |comment| %><br>
<%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
<%= comment.comment %>
<% if comment.user_id == current_user.id %>
<%= link_to "Destroy", book_comment_path(comment.book, comment), method: :delete, remote: true, class: "btn-sm btn-danger" %>
<% end %>
<% end %>
<%= render 'books/show-form', comments: comments %>

app/views/books/_show-form.html.erb
<div class="form-group">
<%= form_with model:[@book, @comment], remote: true do |f| %>
<%= f.text_area :comment, :size=>"100x3",placeholder: " " %>
<%= f.submit "送信する", class: "btn btn-success mb-4" %>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <div class="text-danger">
         <% if @book.errors.any? %>
         <%= @book.errors.count %>
         errors prohibited this obj from being saved:
         <% @book.errors.full_messages.each do |message| %>
          <li>
           <%= message %>
          </li>
         <% end %>
         <% end %>
      </div>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book, user: @user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>
    　　Books
    　</h2>
    　<td id="favorite_button">
    　 <%= render 'books/index', books: @books, user: @user%>
    　</td>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <% if @error_comment.present? %>
      <div id="error_explanation">
      <h2><%= @error_comment.errors.count %></h2>
      <ul>
        <% @error_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <table class='table'>
      <h2>
        User info
      </h2>
      <tr>
      <%= attachment_image_tag @user,:profile_image,fallback: " ", size: "100x100" %>
      </tr>
      <tr>
        <th>
          name
        </th>
        <th>
          <%= @user.name %>
        </th>
      </tr>
      <tr>
        <th>
          introduction
        </th>
        <th>
          <%= @user.introduction %>
        </th>
      </tr>
      </table>
      <div class='row'>
       <%= link_to '',edit_user_path(@user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %>
      </div>
      <h2 class="mt-3">New book</h2>
      <td class="form">
      <%= form_with model: @newbook, local:true do |f| %>
      <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
      <%= f.label :opinion %>
      <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
      <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>
  		  Book detail
  		</h2>
  		<table class='table'>
  		<tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @book.title, book_path(@book) %>
          </td>
          <td>
            <%= @book.body %>
          </td>
              <td>
              <% if @book.user.id == current_user.id %>
              <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-block" %>
              </td>
              <td>
               <%= link_to "Destroy", book_path(@book.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger btn-block"  %>
              </td>
            <% end %>
            <td>
            <div class=<%= 'favorite_buttons_' + @book.id.to_s %> >
            <%= render 'favorites/book-favorite', book: @book, user: @user %>
            </div>
            </td>
            <td>
            コメント件数 <%= @comments.count %>
            </td>
            </table>
      <div id="comment" class=<% 'comment_button_' +  @book.id.to_s %> >
        <%= render partial: 'books/show-comment', locals: {comments: @comments} %>
      </div>
    </div>
    </div>
  </div>
</div>