config/routes.rb
Rails.application.routes.draw do
  get 'favorites/new'
  devise_for :users
  get 'home/about' => 'homes#about'
  root 'homes#top'
  resources :users,only: [:show,:index,:edit,:update] do
   resource :relationships, only: [:create, :destroy]
   get 'follow' => 'relationships#follow', as: 'follow'
   get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :relationships, only: [:index]
  resources :books  do
   resources :comments, only: [:create, :destroy]
   resource :favorite, only: [:create, :destroy]
  end
  post 'book/:id' => 'favorites#create', as: 'create_favorite'
  delete 'book/:id' => 'favorites#destroy', as: 'destroy_favorite'
  root 'homes#top'
  get '/search' => 'searches#search'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
 def search
  @model = params["search"]["model"]
  @value = params["search"]["value"]
  @how = params["search"]["how"]
  @datas = search_for(@how, @model, @value)
 end

private
def match(model, value)
 if model == 'User'
   User.where(name: value)
 elsif model == 'Book'
   Book.where(title: value)
 end
end
def forward(model, value)
 if model == 'User'
   User.where("name LIKE ?", "#{value}%")
 elsif model == 'Book'
   Book.where("title LIKE ?", "#{value}%")
 end
end

def backward(model, value)
 if model == 'User'
   User.where("name LIKE ?", "%#{value}")
 elsif model == 'Book'
   Book.where("title LIKE ?", "%#{value}")
 end
end

def partical(model, value)
 if model == 'User'
   User.where("name LIKE ?", "%#{value}%")
 elsif model == 'Book'
   Book.where("title LIKE ?", "%#{value}%")
 end
end

def search_for(how, model, value)
 case how
 when 'match'
  match(model, value)
 when 'forward'
  forward(model, value)
 when 'backward'
  backward(model, value)
 when 'partical'
  partical(model, value)
 end
end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "User" %>
    <h2>
     Users search for 
    '<%= @value %>'</h2>
    <table class="table">
    <thead>
    <tr>
    <th>
    </th> 
    <th>
     Name
    </th>
    <th>
     Introduction
    </th>
    </tr>
    </thead>
    <% @datas.each do |user| %>
    <tbody>
    <tr>
     <th>
      <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
     </th>
     <th>
     <%= link_to user_path(user.id) do %>
      <%= user.name %>
     <% end %>
     </th>
     <th>
      <%= user.introduction %>
     </th>
     </tr>
     </tbody>
    <% end %>
    <% elsif @model == "Book" %>
    <h2>
     Books search for '<%= @value %>'
    </h2>
    <table class="table">
     <thead>
     <tr>
     <th>
     </th>
     <th>
      Title
     </th>
     <th>
      Opinion
     </th>
     </tr>
     </thead>
     <% @datas.each do |book| %>
     <tbody>
     <tr>
     <th>
      <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
     </th>
     <th>
     <%= link_to book_path(book.id) do %>
      <%= book.title %>
     <% end %>
     </th>
     <th>
      <%= book.body %>
     </th>
     </tr>
     </tbody>
     <% end %>
     <% end %>
    </table>
  </div>
</div>